# $HOME/.config/alacritty/alacritty.toml
# by Mário Moiane 2024-09-30
import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[window]

opacity = 0.7

padding.x = 8
padding.y = 8

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "Inconsolata Nerd Font"
bold.family = "Inconsolata Nerd Font"
italic.family = "Inconsolata Nerd Font"
bold_italic.family = "Inconsolata Nerd Font"

size = 15.0
